name: ptplot-dev-minreqs
channels:
  - conda-forge
  - defaults
dependencies:
  - black==20.8b1
  - bokeh==2.3.3
  - flake8==3.8.4
  - mypy==0.910
  - notebook==6.2.0
  - numpy==1.19.5
  - pandas==1.2.0
  - patsy==0.5.1
  - pip==20.3.3
  - pytest==6.2.1
  - pytest-cov==2.11.1
  - tox==3.21.4
  - pip:
      - svgpathtools==1.4.1
