name: ptplot-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - bokeh
  - flake8
  - mypy
  - notebook
  - numpy
  - pandas
  - patsy
  - pip
  - pytest
  - pytest-cov
  - tox
  - pip:
      - svgpathtools
