name: ptplot-dev-minreqs
channels:
  - conda-forge
  - defaults
dependencies:
  - black==20.8b1
  - flake8==3.8.4
  - notebook==6.2.0
  - numpy==1.19.5
  - pandas==1.2.0
  - pip==20.3.3
  - plotly==4.14.3
  - pytest==6.2.1
  - pytest-cov==2.11.1
  - tox==3.21.4
  - pip:
      - svgpathtools==1.4.1
      - versioneer==0.19
